
---
- name: Download public signing key
  when: inventory_hostname != 'es1'
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch


- name: Add logstash repository file
  when: inventory_hostname != 'es1'
  template:
    src: "templates/logstash.repo.j2"
    dest: "/etc/yum.repos.d/logstash.repo"
    owner: root
    group: root
    mode: 0644

- name: Install Logstash
  when: inventory_hostname != 'es1'
  yum:
   name: logstash
   state: present

- name: Add logstash conf file
  when: inventory_hostname != 'es1'
  template:
    src: "templates/logstash.conf.j2"
    dest: "/etc/logstash/conf.d/logstash.conf"
    owner: root
    group: root
    mode: 0644

# Restart
- name: Restart
  when: inventory_hostname != 'es1'
  ansible.builtin.service:
   name: logstash
   state: restarted

- name: read passwords.txt
  run_once: true
  delegate_to: 'es1'
  shell:
    cmd:  grep "PASSWORD elastic = " {{elasticsearch_path_etc}}passwords.txt | sed -e 's/.*=//'
  register: passwords


- debug:
    msg: "{{ passwords }}"
  run_once: true

- debug:
    msg: "{{ passwords.stdout.split(' ')[1] }}"
  run_once: true

- name: Add passowrd
  when: inventory_hostname != 'es1'
  ansible.builtin.lineinfile:
    destfile: /etc/logstash/conf.d/logstash.conf
    regexp: 'password'
    line: '                       password =>  "{{ passwords.stdout.split(" ")[1] }}"'

- name: restart
  when: inventory_hostname != 'es1'
  ansible.builtin.service:
   name: logstash
   state: restarted
   enabled: yes
