---
- name: Check Java if already installed
  shell: command -v java
  register: check_java
  ignore_errors: True
  changed_when: False
 
- debug:  msg="Java not installed"
  when: check_java.rc > 0

- name: Install Java
  ansible.builtin.shell: yum install java-openjdk -y
  when:  check_java.rc > 0
