- name: Download public signing key
  when: inventory_hostname == 'kib'
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add kibana repository file
  when: inventory_hostname == 'kib'
  template:
    src: "templates/kibana.repo.j2"
    dest: "/etc/yum.repos.d/kibana.repo"
    owner: root
    group: root
    mode: 0644

- name: Install Kibana
  when: inventory_hostname == 'kib'
  yum:
   name: kibana
   state: present

- name: Copying the main config file...
  when: inventory_hostname == 'kib'
  template: src=templates/kibana.yml.j2 dest=/etc/kibana/kibana.yml owner=root group=root mode=0644
  become: true

- name: enable and start
  when: inventory_hostname == 'kib'
  ansible.builtin.service:
   name: kibana
   state: started
   enabled: yes

- name: read passwords.txt
  run_once: true
  delegate_to: es1
  shell:
    cmd:  grep "PASSWORD kibana = " {{elasticsearch_path_etc}}passwords.txt | sed -e 's/.*=//'

  register: passwords


- debug:
    msg: "{{ passwords }}"
  run_once: true

- debug:
    msg: "{{ passwords.stdout.split(' ')[1] }}"
  run_once: true

- name: Add passowrd
  when: inventory_hostname == 'kib'
  ansible.builtin.lineinfile:
    destfile: /etc/kibana/kibana.yml
    line: 'elasticsearch.password: "{{ passwords.stdout.split(" ")[1] }}"'

- name: restart
  when: inventory_hostname == 'kib'
  ansible.builtin.service:
   name: kibana
   state: restarted
   enabled: yes
